XLK - Technology<br>
XLE - Energy<br>
XLF - Financials<br>
XLV - Health Care<br>
XLRE -  Real Estate<br>
XLB - Materials<br>
XLY - Consumer Discretionary<br>
XLP - Consumer Staples<br>
XLU - Utilities<br>
XLI - Industrials<br>
IYZ - Telecommunications<br>

In [3]:
import pandas as pd
from pandas_datareader import data as wb

stocks = []
f = open("sectors.txt","r")
for line in f:
    stocks.append(line.strip())
f.close()

wb.DataReader(stocks,"yahoo", start="2020-1-1",end="2021-11-05")["Adj Close"].to_csv("adjcloseSectors.csv")

In [4]:
stocks = pd.read_csv('adjcloseSectors.csv')
stocks['Date'] = pd.to_datetime(stocks.Date)
stocks.set_index('Date',inplace=True)
stocks.pct_change().agg(['idxmin', 'min'])

,XLK,XLE,XLF,XLV,XLRE,XLB,XLY,XLP,XLU,XLI,IYZ
idxmin,2020-03-16 00:00:00,2020-03-09 00:00:00,2020-03-16 00:00:00,2020-03-16 00:00:00,2020-03-16 00:00:00,2020-03-16 00:00:00,2020-03-16 00:00:00,2020-03-12 00:00:00,2020-03-16 00:00:00,2020-03-16 00:00:00,2020-03-12 00:00:00
min,-0.13814,-0.201412,-0.137093,-0.09861,-0.160011,-0.110084,-0.126686,-0.093956,-0.113577,-0.113441,-0.08758

In [5]:
stocks_df = stocks.pct_change()

In [6]:
stocks_df.tail()

,XLK,XLE,XLF,XLV,XLRE,XLB,XLY,XLP,XLU,XLI,IYZ
Date,,,,,,,,,,,
2021-11-01,-0.001486,0.017226,0.000497,-0.001196,0.002300,0.002350,0.018345,0.001544,0.003587,0.002775,0.010692
2021-11-02,0.008804,-0.009408,0.002483,0.006285,0.009389,0.011369,-0.006737,0.006726,0.000893,0.003340,0.018979
2021-11-03,0.005839,-0.008289,0.003715,0.005874,0.005787,0.010430,0.017989,0.009326,-0.003720,-0.002188,0.012824
2021-11-04,0.015642,0.001393,-0.013077,-0.006874,-0.011303,-0.000573,0.013470,0.000965,-0.005526,0.004004,-0.014471
2021-11-05,0.005174,0.013041,0.000500,-0.011164,0.002286,0.007804,0.006431,0.005787,0.009461,0.010160,0.012236

In [27]:
pd.to_numeric(stocks_df.iloc[1][:-2])

XLK    -0.011243
XLE    -0.002971
XLF    -0.010618
XLV    -0.008714
XLRE    0.007326
XLB    -0.016145
XLY    -0.008510
XLP    -0.001600
XLU     0.002037
XLI    -0.001927
IYZ    -0.005351
Name: 2020-01-03 00:00:00, dtype: float64

In [7]:
stocks_df['best_sector'] = stocks_df.idxmax(axis=1)
stocks_df['worst_sector'] = stocks_df[stocks_df.columns.difference(['best_sector'])].idxmin(axis=1)

In [33]:
stocks_df.head(20)

,XLK,XLE,XLF,XLV,XLRE,XLB,XLY,XLP,XLU,XLI,IYZ,best_sector,worst_sector
Date,,,,,,,,,,,,,
2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03,-0.011243,-0.002971,-0.010618,-0.008714,0.007326,-0.016145,-0.008510,-0.001601,0.002037,-0.001928,-0.005351,XLRE,XLB
2020-01-06,0.002383,0.007781,-0.000650,0.006223,0.000260,-0.004354,0.002782,0.002084,0.000938,0.000362,0.001345,XLE,XLB
2020-01-07,-0.000432,-0.002629,-0.006508,-0.001963,-0.010906,-0.001177,-0.001585,-0.007679,-0.001406,-0.002051,-0.002686,XLK,XLRE
2020-01-08,0.010700,-0.016472,0.006551,0.006492,0.004988,0.003536,0.003016,0.003708,-0.000469,0.003385,0.004040,XLK,XLE
2020-01-09,0.011336,0.007369,0.006183,0.004300,-0.000261,0.003691,0.005302,0.007067,0.005479,0.004217,0.000000,XLK,XLRE
2020-01-10,-0.002326,-0.005653,-0.007439,0.000292,0.009668,-0.004012,-0.005432,-0.000638,0.002647,-0.007079,-0.005366,XLRE,XLF
2020-01-13,0.012507,0.000334,0.006843,-0.003502,0.012164,0.012924,0.003166,0.006543,0.006056,0.008217,0.004383,XLB,XLV
2020-01-14,-0.004711,0.000167,-0.001942,0.006052,-0.004858,-0.004143,-0.000316,0.000317,0.002933,0.000120,-0.000336,XLV,XLRE
2020-01-15,0.001157,-0.007353,-0.005512,0.008636,0.006937,0.006822,-0.002289,0.007133,0.014004,0.001558,0.001007,XLU,XLE
2020-01-16,0.013447,0.001683,0.008803,0.005195,0.008931,0.005949,0.008939,0.002675,0.006222,0.009932,0.011741,XLK,XLE
2020-01-17,0.006738,-0.006387,0.002909,0.000000,0.001265,0.004436,0.003528,0.001727,0.006938,0.000118,0.004310,XLU,XLE
2020-01-21,-0.000412,-0.017930,-0.008379,0.001053,0.010104,-0.010795,-0.003047,0.003447,0.009137,-0.011018,0.003301,XLRE,XLE
2020-01-22,0.003605,-0.009645,0.002925,0.001243,-0.008002,-0.003968,-0.000470,0.000781,0.003117,-0.005271,0.005923,IYZ,XLE
2020-01-23,0.004721,-0.003826,-0.002592,-0.005061,0.009579,-0.001162,0.001490,-0.000936,0.008878,0.010838,-0.002944,XLI,XLV
2020-01-24,-0.004699,-0.011522,-0.012671,-0.016699,-0.001498,-0.007146,-0.013936,-0.006872,0.002640,-0.004646,0.000000,XLU,XLV
2020-01-27,-0.023812,-0.027729,-0.015466,-0.007613,-0.004251,-0.021594,-0.014927,-0.003145,-0.002487,-0.018911,-0.011811,XLU,XLE
2020-01-28,0.019136,0.004541,0.011698,0.004917,0.002511,0.011292,0.009753,0.001262,0.004106,0.006466,0.006972,XLK,XLP
2020-01-29,0.002579,-0.010488,-0.001652,-0.002740,-0.005260,0.003214,-0.000559,-0.005042,0.002629,0.005333,-0.022420,XLI,IYZ
2020-01-30,0.008644,0.008041,0.012575,-0.007262,0.002266,-0.006239,-0.001677,0.011877,0.009323,0.001085,0.000675,XLF,XLV

In [8]:
stocks_df['best_sector'].value_counts()

XLE     117
XLK      76
XLU      56
XLY      41
XLRE     39
XLF      38
XLV      31
XLB      22
XLP      19
XLI      15
IYZ      12
Name: best_sector, dtype: int64

In [9]:
stocks_df['worst_sector'].value_counts()

XLE     143
XLU      64
XLK      50
XLRE     44
XLV      38
XLP      28
XLB      24
XLY      23
XLF      22
IYZ      18
XLI      12
Name: worst_sector, dtype: int64

In [37]:
import numpy as np

df={'a1':[5,6,3,2,5],'a2':[23,43,56,2,6], 'a3':[4,2,3,6,7], 'a4':[1,2,1,3,2],'a5':[4,98,23,5,7],'a6':[5,43,3,2,5]}

x=pd.DataFrame(df).T

rslt = pd.DataFrame(np.zeros((0,3)), columns=['top1','top2','top3'])
for i in x.columns:
    df1row = pd.DataFrame(x.nlargest(3, i).index.tolist(), index=['top1','top2','top3']).T
    rslt = pd.concat([rslt, df1row], axis=0)

print(rslt)

  top1 top2 top3
0   a2   a1   a6
0   a5   a2   a6
0   a2   a5   a1
0   a3   a5   a4
0   a3   a5   a2

In [38]:
df

{'a1': [5, 6, 3, 2, 5],
 'a2': [23, 43, 56, 2, 6],
 'a3': [4, 2, 3, 6, 7],
 'a4': [1, 2, 1, 3, 2],
 'a5': [4, 98, 23, 5, 7],
 'a6': [5, 43, 3, 2, 5]}

In [39]:
x

     0   1   2  3  4
a1   5   6   3  2  5
a2  23  43  56  2  6
a3   4   2   3  6  7
a4   1   2   1  3  2
a5   4  98  23  5  7
a6   5  43   3  2  5

In [11]:
x=stocks_df.T

In [22]:
x.iloc[1]

Date
2020-01-02         NaN
2020-01-03   -0.002971
2020-01-06    0.007781
2020-01-07   -0.002628
2020-01-08   -0.016472
                ...
2021-11-01    0.017226
2021-11-02   -0.009408
2021-11-03   -0.008289
2021-11-04    0.001393
2021-11-05    0.013041
Name: XLE, Length: 467, dtype: object

In [33]:
pd.to_numeric(x[x.columns[1]][:-2]).nlargest(3)

XLRE    0.007326
XLU     0.002037
XLP    -0.001600
Name: 2020-01-03 00:00:00, dtype: float64

In [42]:
x = x.iloc[:-2,1:]

In [43]:
x

Date,2020-01-03,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-13,2020-01-14,2020-01-15,2020-01-16,...,2021-10-25,2021-10-26,2021-10-27,2021-10-28,2021-10-29,2021-11-01,2021-11-02,2021-11-03,2021-11-04,2021-11-05
XLK,-0.011243,0.002383,-0.000432,0.010701,0.011336,-0.002326,0.012506,-0.00471,0.001157,0.013447,...,0.003283,0.002832,-0.000878,0.010048,0.00429,-0.001486,0.008804,0.005839,0.015642,0.005174
XLE,-0.002971,0.007781,-0.002628,-0.016472,0.007369,-0.005653,0.000334,0.000167,-0.007353,0.001683,...,0.014668,0.005782,-0.028745,0.007138,-0.006569,0.017226,-0.009408,-0.008289,0.001393,0.013041
XLF,-0.010618,-0.00065,-0.006508,0.006551,0.006183,-0.007438,0.006843,-0.001942,-0.005512,0.008803,...,-0.001231,0.000739,-0.016502,0.012271,-0.003958,0.000497,0.002483,0.003715,-0.013077,0.0005
XLV,-0.008714,0.006223,-0.001963,0.006491,0.0043,0.000292,-0.003502,0.006052,0.008636,0.005195,...,0.001215,0.004931,-0.007926,0.00837,0.009734,-0.001196,0.006285,0.005874,-0.006874,-0.011164
XLRE,0.007326,0.00026,-0.010906,0.004988,-0.000261,0.009668,0.012164,-0.004858,0.006937,0.008931,...,0.002936,0.0046,-0.007284,0.014675,-0.011984,0.0023,0.009389,0.005787,-0.011303,0.002286
XLB,-0.016145,-0.004354,-0.001177,0.003536,0.003691,-0.004012,0.012924,-0.004143,0.006822,0.005949,...,0.01002,0.002801,-0.014316,0.009918,-0.004794,0.00235,0.011369,0.01043,-0.000573,0.007804
XLY,-0.00851,0.002782,-0.001585,0.003016,0.005302,-0.005432,0.003166,-0.000316,-0.002289,0.008939,...,0.024799,0.000152,0.002227,0.013283,0.002592,0.018345,-0.006737,0.017989,0.01347,0.006431
XLP,-0.0016,0.002084,-0.007679,0.003708,0.007067,-0.000638,0.006543,0.000317,0.007132,0.002676,...,-0.000701,0.003509,-0.005875,0.003518,-0.000981,0.001544,0.006726,0.009326,0.000965,0.005787
XLU,0.002037,0.000938,-0.001406,-0.000469,0.005479,0.002647,0.006056,0.002932,0.014004,0.006223,...,-0.004312,0.005376,-0.006684,0.00658,-0.005943,0.003587,0.000893,-0.00372,-0.005526,0.009461
XLI,-0.001927,0.000362,-0.002051,0.003385,0.004217,-0.00708,0.008218,0.00012,0.001558,0.009932,...,0.00229,-0.006188,-0.011687,0.012504,0.000287,0.002775,0.00334,-0.002188,0.004004,0.01016
IYZ,-0.005351,0.001345,-0.002686,0.00404,0.0,-0.005365,0.004383,-0.000336,0.001007,0.011741,...,-0.006182,0.001555,-0.006832,0.001563,-0.007181,0.010692,0.018979,0.012824,-0.014471,0.012236

In [47]:
x = x.astype('float16')

In [48]:
x.dtypes

Date
2020-01-03    float16
2020-01-06    float16
2020-01-07    float16
2020-01-08    float16
2020-01-09    float16
               ...
2021-11-01    float16
2021-11-02    float16
2021-11-03    float16
2021-11-04    float16
2021-11-05    float16
Length: 466, dtype: object

In [60]:
rslt = pd.DataFrame([], columns=['top1','top2','top3','bottom1','bottom2','bottom3'])

In [61]:
rslt

Empty DataFrame
Columns: [top1, top2, top3, bottom1, bottom2, bottom3]
Index: []

In [62]:
for i in x.columns:
    df1row = pd.DataFrame(x.nlargest(3, i).index.tolist()+x.nsmallest(3, i).index.tolist(), index=['top1','top2','top3','bottom1','bottom2','bottom3'],columns=[i]).T
    rslt = pd.concat([rslt, df1row], axis=0)

In [50]:
x.columns

DatetimeIndex(['2020-01-03', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10', '2020-01-13', '2020-01-14',
               '2020-01-15', '2020-01-16',
               ...
               '2021-10-25', '2021-10-26', '2021-10-27', '2021-10-28',
               '2021-10-29', '2021-11-01', '2021-11-02', '2021-11-03',
               '2021-11-04', '2021-11-05'],
              dtype='datetime64[ns]', name='Date', length=466, freq=None)

In [51]:
x

Date,2020-01-03,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-13,2020-01-14,2020-01-15,2020-01-16,...,2021-10-25,2021-10-26,2021-10-27,2021-10-28,2021-10-29,2021-11-01,2021-11-02,2021-11-03,2021-11-04,2021-11-05
XLK,-0.011246,0.002382,-0.000432,0.010704,0.011337,-0.002327,0.012505,-0.004711,0.001157,0.013443,...,0.003283,0.002832,-0.000878,0.010048,0.004292,-0.001486,0.008804,0.005840,0.015640,0.005173
XLE,-0.002972,0.007782,-0.002628,-0.016464,0.007370,-0.005653,0.000335,0.000167,-0.007355,0.001683,...,0.014671,0.005783,-0.028748,0.007137,-0.006569,0.017227,-0.009407,-0.008286,0.001393,0.013039
XLF,-0.010620,-0.000650,-0.006508,0.006550,0.006184,-0.007439,0.006844,-0.001942,-0.005512,0.008804,...,-0.001231,0.000740,-0.016510,0.012268,-0.003960,0.000497,0.002483,0.003716,-0.013077,0.000500
XLV,-0.008713,0.006222,-0.001963,0.006493,0.004299,0.000292,-0.003502,0.006054,0.008636,0.005196,...,0.001215,0.004932,-0.007927,0.008369,0.009735,-0.001196,0.006283,0.005875,-0.006874,-0.011162
XLRE,0.007324,0.000260,-0.010910,0.004990,-0.000261,0.009666,0.012161,-0.004856,0.006939,0.008934,...,0.002935,0.004601,-0.007282,0.014671,-0.011986,0.002300,0.009392,0.005787,-0.011299,0.002287
XLB,-0.016144,-0.004353,-0.001178,0.003536,0.003691,-0.004013,0.012924,-0.004143,0.006821,0.005951,...,0.010017,0.002802,-0.014313,0.009918,-0.004795,0.002350,0.011368,0.010429,-0.000574,0.007805
XLY,-0.008507,0.002781,-0.001585,0.003016,0.005302,-0.005432,0.003166,-0.000315,-0.002289,0.008942,...,0.024796,0.000152,0.002228,0.013283,0.002592,0.018341,-0.006737,0.017990,0.013474,0.006432
XLP,-0.001600,0.002085,-0.007679,0.003708,0.007069,-0.000638,0.006542,0.000317,0.007133,0.002676,...,-0.000701,0.003510,-0.005875,0.003517,-0.000981,0.001544,0.006725,0.009323,0.000966,0.005787
XLU,0.002037,0.000938,-0.001407,-0.000469,0.005478,0.002647,0.006058,0.002932,0.014008,0.006222,...,-0.004311,0.005375,-0.006683,0.006580,-0.005943,0.003588,0.000894,-0.003719,-0.005527,0.009460
XLI,-0.001927,0.000362,-0.002050,0.003386,0.004219,-0.007080,0.008217,0.000120,0.001558,0.009933,...,0.002291,-0.006187,-0.011688,0.012505,0.000287,0.002775,0.003340,-0.002188,0.004005,0.010162
IYZ,-0.005352,0.001345,-0.002686,0.004040,0.000000,-0.005367,0.004383,-0.000336,0.001007,0.011742,...,-0.006184,0.001555,-0.006832,0.001563,-0.007179,0.010689,0.018982,0.012825,-0.014473,0.012238

In [58]:
x.nlargest(3, x.columns[3]).index

Index(['XLK', 'XLF', 'XLV'], dtype='object')

In [69]:
pd.DataFrame(x.nlargest(3, x.columns[1]).index.tolist()+x.nsmallest(3, x.columns[1]).index.tolist(), index=['top1','top2','top3','bottom1','bottom2','bottom3'],columns=[x.columns[1]]).T

            top1 top2 top3 bottom1 bottom2 bottom3
2020-01-03  XLRE  XLU  XLP     XLB     XLK     XLF

In [63]:
rslt.shape

(466, 6)

In [68]:
stocks_df.tail(1)

,XLK,XLE,XLF,XLV,XLRE,XLB,XLY,XLP,XLU,XLI,IYZ
Date,,,,,,,,,,,
2020-10-26,-0.021699,-0.035867,-0.022574,-0.01113,-0.012068,-0.025,-0.019217,-0.012846,-0.000309,-0.025009,-0.014855

In [53]:
(rslt['top1'].value_counts()+rslt['top2'].value_counts()+rslt['top3'].value_counts()).sort_values(ascending=False)

XLK     167
XLE     163
XLU     151
XLRE    141
XLY     132
XLF     131
XLV     124
XLB     113
XLP     101
XLI     100
IYZ      75
dtype: int64

In [54]:
(rslt['bottom1'].value_counts()+rslt['bottom2'].value_counts()+rslt['bottom3'].value_counts()).sort_values(ascending=False)

XLE     211
XLU     150
XLF     147
XLRE    132
XLK     131
XLV     119
XLP     113
XLY     105
XLB     104
XLI      97
IYZ      89
dtype: int64